### ISSUE TITLE
java.lang.NullPointerException when upgraded to kotlin 2.0

### ISSUE THREAD

**Issue by hanrw** [mockito/mockito-kotlin#519]
test
```kotlin
@ExtendWith(MockitoExtension::class)
class UserStatusServiceTest {
    @InjectMocks
    lateinit var target: UserStatusServiceImpl

    @Mock
    lateinit var userStatusRepository: UserStatusRepository

    @Test
    fun addStatus() {
        whenever(
            userStatusRepository.findByUserId(
                1L,
            )
        ).thenReturn(
            Optional.empty()
        )

        target.addStatus(1L)

        val suspension = UserStatus()
        verify(userStatusRepository).save(suspension)
    }
}
```
service
```kotlin
interface UserStatusService {
    fun addStatus(userId: Long)
}

class UserStatusServiceImpl(private val userStatusRepository: UserStatusRepository) :
    UserStatusService {
    override fun addStatus(userId: Long) {
        val optional = userStatusRepository.findByUserId(userId)
        if (optional.isEmpty) {
            println("[userId: $userId] adding a new status")

            userStatusRepository.save(UserStatus())
        } else {
            println("[userId: $userId] status already exists")
        }
    }
}
```

repository
```kotlin
@Repository
interface UserStatusRepository : JpaRepository<UserStatus, Long>,
    JpaSpecificationExecutor<UserStatus> {
    fun findByUserId(userId: Long): Optional<UserStatus>
}

data class UserStatus(
    val userId: Long = 1L
)
```

and got error
```shell
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
[userId: 1] adding a new status

java.lang.NullPointerException
	at com.kotlin.npe.reporduce.UserStatusServiceImpl.addStatus(UserStatusService.kt:11)
	at com.kotlin.npe.reporduce.UserStatusServiceTest.addStatus(UserStatusServiceTest.kt:31)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

here's reproduce repo 
[archive.zip](https://github.com/user-attachments/files/15880408/archive.zip)

**Comment by lasficw** [comment]
We have the same Problem, is there something we can do about it?

**Comment by Vladimir-Buttn** [comment]
+1 here

**Comment by heliming** [comment]
+1

**Comment by silviuburceadev** [comment]
I am facing the same issue. My setup:

```
@ExtendWith(MockitoExtension::class)
internal class MyTest {
  @Mock
  private lateinit var myRepository: MyRepository

  @Mock
  private lateinit var myService: MyService

  // depends on myRepository and myService
  @InjectMocks
  private lateinit var myCompositeService: MyCompositeService
}
```

`MyRepository` is a org.springframework.data.repository.CrudRepository, no annotations, and `MyService` is a classic `@Service` class.

Even though I'm checking that myRepository is not null, both in the test class, before calling the method tested and inside the method, before the repository does a save. And yet, `myRepository.save` fails with NPE.

**Comment by silviuburceadev** [comment]
@hanrw I have tested my finding on your reproducible project. You have a commented-out line there, replace it with:
```java
whenever(userStatusRepository.save(any<UserStatus>()))
            .thenAnswer(returnsFirstArg<UserStatus>())
```
... and it works.
